# Site settings
title: MiguelLara.github.io
email: miguel@mac.com
description: >
  Notes to myself, hints, fixes and ramblings –specially about Swift–,
  that may be useful to others.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://miguellara.github.io" # the base hostname & protocol for your site
twitter_username: bigbrowntheory
github_username:  miguellara

exclude: ["Gemfile", "Gemfile.lock"]

# Build settings
markdown: kramdown
