name: Miguel Lara's Coding Blog
description: Notes to myself, hints, fixes and ramblings –specially about Swift.
#meta_description: "Your New Jekyll Site, Blogging about stuffs"

aboutPage: false

paginate: 20
baseurl: /
domain_name: 'http://miguellara.github.io'

twitter_username: bigbrowntheory
github_username:  miguellara

# Integrations
#google_analytics: 'UA-XXXXXXXX-X'
#disqus: false
#disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://miguellara.github.io'
author:         'Miguel Lara <miguel@mac.com>'
authorTwitter:  'bigbrowntheory'

# URL
permalink:       /:year/:title/

# Build settings
markdown: redcarpet
highlighter: pygments
gems: [jekyll-gist, jekyll-paginate]
exclude: ["Gemfile", "Gemfile.lock"]


sass:
    sass_dir: assets/css
    style: compressed

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
